# PIPELINE DEFINITION
# Name: ml-pipeline
components:
  comp-data-collector:
    executorLabel: exec-data-collector
  comp-data-processor:
    executorLabel: exec-data-processor
deploymentSpec:
  executors:
    exec-data-collector:
      container:
        args:
        - cli.py
        - --search
        - --nums 10
        - --query oyster+mushrooms crimini+mushrooms amanita+mushrooms
        - --bucket mushroom-app-ml-workflow-demo
        image: dlops/mushroom-app-data-collector
    exec-data-processor:
      container:
        args:
        - cli.py
        - --clean
        - --prepare
        - --bucket mushroom-app-ml-workflow-demo
        image: dlops/mushroom-app-data-processor
pipelineInfo:
  name: ml-pipeline
root:
  dag:
    tasks:
      data-collector:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-collector
        taskInfo:
          name: Data Collector
      data-processor:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-processor
        dependentTasks:
        - data-collector
        taskInfo:
          name: Data Processor
schemaVersion: 2.1.0
sdkVersion: kfp-2.3.0
